version: 2

sources:
  - name: treytrey_de_project  # Dataset Name
    description: "Source dataset in BigQuery"
    database: lewagon-dataengineering-tc  # GCP Project ID
    schema: treytrey_de_project  # Dataset Name (same as `name` above)
    tables:
    - name: categories
      description: "Contains product category information for products"
      columns:
        - name: category_id
          description: "Primary key for product categories"
          tests:
            - unique
            - not_null

    - name: customers
      description: "Contains customer details"
      columns:
        - name: customer_id
          description: "Primary key for customers"
          tests:
            - unique
            - not_null

    - name: departments
      description: "List of departments"
      columns:
        - name: department_id
          description: "Primary key for departments"
          tests:
            - unique
            - not_null

    - name: order_items
      description: "Details of order line items for each purchase"
      columns:
        - name: order_item_id
          description: "Primary key for order items"
          tests:
            - unique
            - not_null

    - name: orders
      description: "Main orders table containing all purchases"
      columns:
        - name: order_id
          description: "Primary key for orders"
          tests:
            - unique
            - not_null

    - name: products
      description: "Product catalog with details of each item"
      columns:
        - name: product_id
          description: "Primary key for products"
          tests:
            - unique
            - not_null